// Verifiable quotations from published works. Wording follows standard
// public-domain translations where applicable (Legge for Laozi/Confucius,
// Giles for Sunzi, Carter/Long for Epictetus, Long for Marcus Aurelius,
// Jowett for Plato, Ross for Aristotle, Adams for Hippocrates).

export const dailyQuotes = [
  { text: "It is not that we have a short time to live, but that we waste much of it. Life is long enough, and a sufficiently generous amount has been given to us for the highest achievements if it were all well invested.", source: "Seneca · On the Shortness of Life" },
  { text: "While we are postponing, life speeds by. Nothing is ours, except time.", source: "Seneca · Letters to Lucilius, I" },
  { text: "We suffer more often in imagination than in reality.", source: "Seneca · Letters to Lucilius, XIII" },
  { text: "As long as you live, keep learning how to live.", source: "Seneca · Letters to Lucilius, LXXVI" },
  { text: "Confine yourself to the present.", source: "Marcus Aurelius · Meditations, VII" },
  { text: "Do every act of your life as though it were the last act of your life.", source: "Marcus Aurelius · Meditations, II" },
  { text: "Loss is nothing else but change, and change is Nature's delight.", source: "Marcus Aurelius · Meditations, IX" },
  { text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", source: "Marcus Aurelius · Meditations, VII" },
  { text: "No longer talk at all about the kind of man that a good man ought to be, but be such.", source: "Marcus Aurelius · Meditations, X" },
  { text: "The tree which fills the arms grew from the tiniest sprout; the tower of nine storeys rose from a small heap of earth; the journey of a thousand li commenced with a single step.", source: "Laozi · Tao Te Ching, 64" },
  { text: "He who knows other men is discerning; he who knows himself is intelligent. He who overcomes others is strong; he who overcomes himself is mighty.", source: "Laozi · Tao Te Ching, 33" },
  { text: "He who stands on his tiptoes does not stand firm; he who stretches his legs does not walk easily.", source: "Laozi · Tao Te Ching, 24" },
  { text: "The master of the Tao anticipates things that are difficult while they are easy, and does things that would become great while they are small.", source: "Laozi · Tao Te Ching, 63" },
  { text: "If you know the enemy and know yourself, you need not fear the result of a hundred battles.", source: "Sunzi · The Art of War, III" },
  { text: "The skilful commander takes up a position in which he cannot be defeated, and misses no opportunity of mastering his enemy.", source: "Sunzi · The Art of War, IV" },
  { text: "The general who wins a battle makes many calculations in his temple before the battle is fought.", source: "Sunzi · The Art of War, I" },
  { text: "Learning without thought is labour lost; thought without learning is perilous.", source: "Confucius · Analects, II" },
  { text: "When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it: this is knowledge.", source: "Confucius · Analects, II" },
  { text: "The cautious seldom err.", source: "Confucius · Analects, IV" },
  { text: "The superior man is modest in his speech, but exceeds in his actions.", source: "Confucius · Analects, XIV" },
  { text: "To go beyond is as wrong as to fall short.", source: "Confucius · Analects, XI" },
  { text: "The unexamined life is not worth living.", source: "Plato · Apology" },
  { text: "The beginning is the most important part of the work.", source: "Plato · Republic, II" },
  { text: "Men are disturbed not by the things that happen, but by their opinions about the things.", source: "Epictetus · Enchiridion, 5" },
  { text: "First say to yourself what you would be; and then do what you have to do.", source: "Epictetus · Discourses, III" },
  { text: "In every affair consider what precedes and what follows, and then undertake it.", source: "Epictetus · Enchiridion, 29" },
  { text: "You cannot step twice into the same river, for other waters are continually flowing on.", source: "Heraclitus, quoted in Plato · Cratylus" },
  { text: "The sun is new each day.", source: "Heraclitus · Fragments" },
  { text: "The virtues we get by first exercising them, as also happens in the case of the arts: the things we have to learn before we can do them, we learn by doing them.", source: "Aristotle · Nicomachean Ethics, II" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", source: "Will Durant · The Story of Philosophy" },
  { text: "Life is short, and the art long; the occasion fleeting; experience fallacious, and judgment difficult.", source: "Hippocrates · Aphorisms, I.1" },
  { text: "Dripping water hollows out stone, not through force but through persistence.", source: "Ovid · Epistulae ex Ponto, IV.10" },
  { text: "Practice is the best of all instructors.", source: "Publilius Syrus · Sentences" },
  { text: "It is a bad plan that admits of no modification.", source: "Publilius Syrus · Sentences" },
  { text: "He who has begun is half done: dare to be wise, begin.", source: "Horace · Epistles, I.2" },
  { text: "To every thing there is a season, and a time to every purpose under the heaven.", source: "Ecclesiastes 3:1 (King James Version)" },
  { text: "Great works are performed not by strength but by perseverance.", source: "Samuel Johnson · Rasselas" },
  { text: "I have made this longer than usual because I have not had time to make it shorter.", source: "Blaise Pascal · Lettres provinciales, XVI" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", source: "Johann Wolfgang von Goethe · Wilhelm Meister" },
  { text: "Great things are not done by impulse, but by a series of small things brought together.", source: "Vincent van Gogh · letter to Theo, 1882" },
  { text: "Perfection is attained not when there is nothing more to add, but when there is nothing more to take away.", source: "Antoine de Saint-Exupéry · Wind, Sand and Stars" },
  { text: "In the fields of observation, chance favours only the prepared mind.", source: "Louis Pasteur · lecture at Lille, 1854" },
  { text: "If I have seen further it is by standing on the shoulders of giants.", source: "Isaac Newton · letter to Robert Hooke, 1675" },
  { text: "Nothing is too wonderful to be true, if it be consistent with the laws of nature.", source: "Michael Faraday · laboratory notebook, 1849" },
  { text: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.", source: "Marie Curie" },
  { text: "Science is built up of facts, as a house is built of stones; but an accumulation of facts is no more a science than a heap of stones is a house.", source: "Henri Poincaré · Science and Hypothesis" },
  { text: "The Analytical Engine has no pretensions whatever to originate anything. It can do whatever we know how to order it to perform.", source: "Ada Lovelace · Notes on the Analytical Engine, 1843" },
  { text: "Any man could, if he were so inclined, be the sculptor of his own brain.", source: "Santiago Ramón y Cajal · Advice for a Young Investigator" },
  { text: "From so simple a beginning endless forms most beautiful and most wonderful have been, and are being, evolved.", source: "Charles Darwin · On the Origin of Species" },
  { text: "It is not enough to be busy; so are the ants. The question is: what are we busy about?", source: "Henry David Thoreau · letter to H. G. O. Blake, 1857" },
  { text: "As if you could kill time without injuring eternity.", source: "Henry David Thoreau · Walden" },
  { text: "Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can.", source: "Ralph Waldo Emerson · letter, 1854" },
  { text: "The reward of a thing well done is having done it.", source: "Ralph Waldo Emerson · Essays: Second Series" },
  { text: "My experience is what I agree to attend to.", source: "William James · The Principles of Psychology" },
  { text: "Nothing is so fatiguing as the eternal hanging on of an uncompleted task.", source: "William James · essay, 1899" },
  { text: "How we spend our days is, of course, how we spend our lives.", source: "Annie Dillard · The Writing Life" },
  { text: "Order and simplification are the first steps toward the mastery of a subject.", source: "Thomas Mann · The Magic Mountain" },
  { text: "Iron rusts from disuse; water loses its purity from stagnation; even so does inaction sap the vigour of the mind.", source: "Leonardo da Vinci · Notebooks" },
  { text: "The noblest pleasure is the joy of understanding.", source: "Leonardo da Vinci · Notebooks" },
  { text: "Dost thou love life? Then do not squander time, for that is the stuff life is made of.", source: "Benjamin Franklin · Poor Richard's Almanack" },
  { text: "Energy and persistence conquer all things.", source: "Benjamin Franklin" },
  { text: "Genius is one per cent inspiration and ninety-nine per cent perspiration.", source: "Thomas Edison, 1902" },
  { text: "Work expands so as to fill the time available for its completion.", source: "C. Northcote Parkinson · The Economist, 1955" },
  { text: "Our main business is not to see what lies dimly at a distance, but to do what lies clearly at hand.", source: "Thomas Carlyle · Signs of the Times" },
  { text: "I attribute my success to this: I never gave or took an excuse.", source: "Florence Nightingale" },
  { text: "He who would learn to fly one day must first learn to stand and walk and run and climb and dance; one cannot fly into flying.", source: "Friedrich Nietzsche · Thus Spoke Zarathustra" },
  { text: "Patience is bitter, but its fruit is sweet.", source: "Jean-Jacques Rousseau · Emile" },
  { text: "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.", source: "Samuel Beckett · Worstward Ho" },
] as const;

export const quoteForDate = (date: Date) => {
  const dayNumber = Math.floor(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86_400_000);
  return dailyQuotes[((dayNumber % dailyQuotes.length) + dailyQuotes.length) % dailyQuotes.length];
};
