import Link from "next/link";
import { ArrowLeft, BookOpen, Check, CircleDot, KeyRound, LockKeyhole } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { authenticate, createFirstUser } from "./actions";
import { count } from "drizzle-orm";
import { db } from "@/db";
import { appUser } from "@/db/schema";

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ setup?: string }> }) {
  const [{ userCount }] = await db.select({ userCount: count() }).from(appUser);
  const isFirstUse = userCount === 0;
  const setupComplete = searchParams ? (await searchParams).setup === "complete" : false;
  const setupError = searchParams ? (await searchParams).setup === "error" : false;

  return <div className="mx-auto flex min-h-[calc(100vh-72px)] max-w-[1200px] items-center justify-center px-5 py-12 sm:px-8"><div className="grid w-full max-w-4xl overflow-hidden border border-ink/15 bg-paper-deep shadow-[0_18px_60px_rgba(43,41,38,.12)] md:grid-cols-[.82fr_1.18fr]"><div className="grid-paper bg-slate p-8 text-paper sm:p-12"><CircleDot className="text-aqua" size={28} /><p className="mt-16 text-[11px] font-bold uppercase tracking-[.18em] text-aqua">Private side</p><h1 className="display mt-3 text-5xl font-bold leading-none">Back to<br />the room.</h1><p className="mt-6 max-w-xs text-sm leading-6 text-paper/60">A quiet place for the people who keep the shared schedule moving.</p><div className="mt-16 flex items-center gap-2 text-xs text-paper/45"><BookOpen size={14} /> RABO / ROOM LOG</div></div><div className="p-8 sm:p-12"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-coral">Admin access</p>{isFirstUse ? <><h2 className="display mt-3 text-3xl font-bold">Set up ranrabo</h2><p className="mt-3 max-w-sm text-sm leading-6 text-ink/60">This is the first visit. Choose a password for the private room log.</p>{setupError && <p className="mt-5 border-l-2 border-coral bg-coral/10 px-3 py-2 text-sm font-bold text-coral">Use at least 12 characters and make both passwords match.</p>}<form action={createFirstUser} className="mt-7 space-y-5"><div><Label htmlFor="setup-username">Username</Label><Input id="setup-username" value="ranrabo" readOnly /></div><div><Label htmlFor="setup-password">Password</Label><Input id="setup-password" name="password" type="password" autoComplete="new-password" minLength={12} required /></div><div><Label htmlFor="confirmation">Confirm password</Label><Input id="confirmation" name="confirmation" type="password" autoComplete="new-password" minLength={12} required /></div><Button type="submit" className="mt-2 w-full"><KeyRound size={16} /> Create private account</Button></form></> : <><h2 className="display mt-3 text-3xl font-bold">Sign in</h2>{setupComplete && <p className="mt-5 flex items-center gap-2 border-l-2 border-slate bg-slate/10 px-3 py-2 text-sm font-bold text-slate"><Check size={15} /> Account ready. Sign in below.</p>}<form action={authenticate} className="mt-8 space-y-5"><div><Label htmlFor="identifier">Username or email</Label><Input id="identifier" name="identifier" type="text" autoComplete="username" required /></div><div><Label htmlFor="password">Password</Label><Input id="password" name="password" type="password" autoComplete="current-password" required /></div><Button type="submit" className="mt-2 w-full"><LockKeyhole size={16} /> Enter admin</Button></form></>}<Link href="/" className="mt-7 flex items-center gap-2 text-sm font-bold text-ink/50 hover:text-coral"><ArrowLeft size={15} /> Back to public schedule</Link></div></div></div>;
}
