import { Clock3, Plus, Save, UserRound, X } from "lucide-react";
import { getAdminToday } from "@/lib/data";
import { formatDate, formatTime } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { addPerson, createManualSession, deactivatePerson, deleteSession, endSession, startSession, updatePerson, updateSession } from "./actions";

export const dynamic = "force-dynamic";

export default async function AdminPage() {
  const { today, people, sessions } = await getAdminToday();
  const activePeople = people.filter((member) => member.active);
  const openIds = new Set(sessions.filter(({ session }) => !session.endTime).map(({ session }) => session.personId));
  return <div className="space-y-12">
    <section><div className="mb-5 flex items-end justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-coral">Quick log</p><h2 className="display mt-2 text-2xl font-bold">What’s happening now?</h2></div><span className="text-sm font-semibold text-ink/45">{formatDate(today)}</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{activePeople.map((member) => { const isOpen = openIds.has(member.id); return <div key={member.id} className="flex items-center justify-between gap-3 rounded-2xl border border-ink/15 bg-white p-4"><div className="min-w-0"><p className="truncate text-sm font-bold">{member.fullName}</p><p className="mt-1 text-xs text-ink/45">{isOpen ? "Currently in the lab" : "Not logged in"}</p></div><div className="flex shrink-0 gap-2">{isOpen ? <form action={endSession}><input type="hidden" name="personId" value={member.id} /><Button type="submit" className="h-10 bg-coral px-3 text-ink hover:bg-coral/80">End session</Button></form> : <form action={startSession}><input type="hidden" name="personId" value={member.id} /><Button type="submit" className="h-10 bg-aqua px-3 text-ink hover:bg-aqua/80">Start session</Button></form>}</div></div>; })}</div></section>

    <section className="rounded-[24px] border border-ink/15 bg-white p-5 sm:p-7"><div className="mb-6 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-periwinkle"><Clock3 size={18} /></span><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-ink/45">After the fact</p><h2 className="display text-2xl font-bold">Manual entry</h2></div></div><form action={createManualSession} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5 lg:items-end"><div><Label htmlFor="manual-person">Person</Label><Select id="manual-person" name="personId" required><option value="">Choose person</option>{activePeople.map((member) => <option key={member.id} value={member.id}>{member.fullName}</option>)}</Select></div><div><Label htmlFor="manual-date">Date</Label><Input id="manual-date" name="sessionDate" type="date" defaultValue={today} required /></div><div><Label htmlFor="manual-start">Start</Label><Input id="manual-start" name="startTime" type="time" required /></div><div><Label htmlFor="manual-end">End <span className="normal-case tracking-normal text-ink/35">(optional)</span></Label><Input id="manual-end" name="endTime" type="time" /></div><div><Label htmlFor="manual-note">Note <span className="normal-case tracking-normal text-ink/35">(optional)</span></Label><Input id="manual-note" name="note" placeholder="e.g. instrument run" /></div><Button type="submit" className="lg:col-span-5 lg:w-fit"><Plus size={16} /> Add manual session</Button></form></section>

    <section><div className="mb-5"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-coral">Today’s log</p><h2 className="display mt-2 text-2xl font-bold">Sessions on record</h2></div>{sessions.length ? <div className="space-y-3">{sessions.map(({ session, member }) => <form action={updateSession} key={session.id} className="grid gap-3 rounded-2xl border border-ink/15 bg-white p-4 sm:grid-cols-[1.2fr_1fr_1fr_1fr_1.4fr_auto_auto] sm:items-end"><input type="hidden" name="id" value={session.id} /><div><Label htmlFor={`person-${session.id}`}>Person</Label><Select id={`person-${session.id}`} name="personId" defaultValue={String(session.personId)}>{people.map((person) => <option key={person.id} value={person.id}>{person.fullName}{!person.active ? " (inactive)" : ""}</option>)}</Select></div><div><Label htmlFor={`date-${session.id}`}>Date</Label><Input id={`date-${session.id}`} name="sessionDate" type="date" defaultValue={session.sessionDate} required /></div><div><Label htmlFor={`start-${session.id}`}>Start</Label><Input id={`start-${session.id}`} name="startTime" type="time" defaultValue={session.startTime.slice(0, 5)} required /></div><div><Label htmlFor={`end-${session.id}`}>End</Label><Input id={`end-${session.id}`} name="endTime" type="time" defaultValue={session.endTime?.slice(0, 5) || ""} /></div><div><Label htmlFor={`note-${session.id}`}>Note</Label><Input id={`note-${session.id}`} name="note" defaultValue={session.note || ""} placeholder="Optional note" /></div><Button type="submit" className="h-11 bg-aqua text-ink hover:bg-aqua/80" aria-label={`Save ${member.fullName} session`}><Save size={16} /> <span className="sm:hidden">Save</span></Button><button formAction={deleteSession} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl px-3 text-sm font-bold text-ink/45 hover:bg-coral/15 hover:text-coral focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-aqua" aria-label={`Delete ${member.fullName} session`}><X size={16} /> <span className="sm:hidden">Delete</span></button></form>)}</div> : <div className="rounded-2xl border border-dashed border-ink/25 px-5 py-8 text-sm text-ink/55">No sessions logged today yet. Use quick log above, or add an earlier visit with manual entry.</div>}</section>

    <section className="border-t border-ink/15 pt-12"><div className="mb-6 flex items-end justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-coral">People management</p><h2 className="display mt-2 text-2xl font-bold">The people in the room</h2></div><UserRound className="text-ink/25" /></div><div className="mb-5 rounded-2xl border border-ink/15 bg-white p-5"><form action={addPerson} className="grid gap-4 sm:grid-cols-[1fr_1.3fr_1.5fr_100px_auto] sm:items-end"><div><Label htmlFor="new-name">Full name</Label><Input id="new-name" name="fullName" required placeholder="Person name" /></div><div><Label htmlFor="new-email">Email</Label><Input id="new-email" name="email" type="email" placeholder="name@example.org" /></div><div><Label htmlFor="new-area">Research area</Label><Input id="new-area" name="researchArea" required placeholder="One short phrase" /></div><div><Label htmlFor="new-order">Order</Label><Input id="new-order" name="sortOrder" type="number" defaultValue="0" /></div><Button type="submit" className="bg-slate"><Plus size={16} /> Add person</Button></form></div><div className="space-y-3">{people.map((member) => <div key={member.id} className="rounded-2xl border border-ink/15 bg-white p-4"><form action={updatePerson} className="grid gap-3 sm:grid-cols-[1fr_1.2fr_1.4fr_80px_auto_auto] sm:items-end"><input type="hidden" name="id" value={member.id} /><div><Label htmlFor={`edit-name-${member.id}`}>Full name</Label><Input id={`edit-name-${member.id}`} name="fullName" defaultValue={member.fullName} required /></div><div><Label htmlFor={`edit-email-${member.id}`}>Email</Label><Input id={`edit-email-${member.id}`} name="email" type="email" defaultValue={member.email || ""} /></div><div><Label htmlFor={`edit-area-${member.id}`}>Research area</Label><Input id={`edit-area-${member.id}`} name="researchArea" defaultValue={member.researchArea} required /></div><div><Label htmlFor={`edit-order-${member.id}`}>Order</Label><Input id={`edit-order-${member.id}`} name="sortOrder" type="number" defaultValue={member.sortOrder} /></div><Button type="submit" className="h-11 bg-periwinkle text-ink hover:bg-periwinkle/80"><Save size={16} /> Save</Button>{member.active ? <button formAction={deactivatePerson} className="h-11 rounded-xl px-3 text-sm font-bold text-coral hover:bg-coral/10">Deactivate</button> : <span className="flex h-11 items-center px-3 text-xs font-bold uppercase tracking-[.12em] text-ink/40">Inactive</span>}</form></div>)}</div></section>
  </div>;
}
